version: 2
jobs:
  build_storybook:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing node modules
          command: |
            npm i
      # storybookをビルドする
      # - run:
      #     name: Generate Storybook
      #     command: |
      #       sh ./scripts/generateStorybookForPr.sh
      - run:
          name: "Generate storybook"
          command: export NODE_OPTIONS="--max-old-space-size=8192"; yarn build-storybook
      - run:
          name: "Post storybook"
          command: export CIRCLE_REPO_ID="22704738"; sh ./scripts/post_storybook.js
      # Artifactsにアップロードする
      - store_artifacts:
          path: ./storybook-static
          destination: ~/storybook
workflows:
  version: 2
  test:
    jobs:
      - build_storybook